# Generated by Django 5.2 on 2025-06-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simbaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ai_model',
            field=models.CharField(choices=[('gpt', 'GPT'), ('mistral', 'Mistral')], default='gpt', max_length=20),
        ),
    ]
