# Generated by Django 5.2 on 2025-04-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simbaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='agent_attitude',
            field=models.CharField(choices=[('friendly', 'Friendly'), ('informal', 'Informal'), ('formal', 'Formal')], default='friendly', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='allow_emojis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='allow_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='custom_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='expert_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='questions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='restrict_to_subject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='trust_document',
            field=models.BooleanField(default=True),
        ),
    ]
