# Generated by Django 5.2 on 2025-06-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simbaapp', '0002_activity_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='never_answer_directly',
            field=models.BooleanField(default=True),
        ),
    ]
