# Generated by Django 5.2 on 2025-07-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simbaapp', '0003_activity_never_answer_directly'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='options',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
