# Generated by Django 5.2 on 2025-07-02 19:30

from django.db import migrations


def migrate_to_options(apps, schema_editor):
    """Move existing field data to options JSON field"""
    Activity = apps.get_model('simbaapp', 'Activity')
    
    for activity in Activity.objects.all():
        options = {}
        
        # Migrate all the fields that will be moved to options
        if activity.questions is not None:
            options['questions'] = activity.questions
        else:
            options['questions'] = []
            
        options['agent_attitude'] = getattr(activity, 'agent_attitude', 'friendly')
        options['subjects'] = getattr(activity, 'subjects', '')
        options['restrict_to_subject'] = getattr(activity, 'restrict_to_subject', False)
        options['allow_questions'] = getattr(activity, 'allow_questions', True)
        options['never_answer_directly'] = getattr(activity, 'never_answer_directly', True)
        options['allow_emojis'] = getattr(activity, 'allow_emojis', True)
        options['trust_document'] = getattr(activity, 'trust_document', True)
        options['word_limit'] = getattr(activity, 'word_limit', 0)
        
        # Set the options field
        activity.options = options
        activity.save(update_fields=['options'])


def reverse_migrate_from_options(apps, schema_editor):
    """Reverse migration: restore data from options to individual fields"""
    Activity = apps.get_model('simbaapp', 'Activity')
    
    for activity in Activity.objects.all():
        if activity.options and isinstance(activity.options, dict):
            options = activity.options
            
            # Restore fields from options
            activity.questions = options.get('questions', [])
            activity.agent_attitude = options.get('agent_attitude', 'friendly')
            activity.subjects = options.get('subjects', '')
            activity.restrict_to_subject = options.get('restrict_to_subject', False)
            activity.allow_questions = options.get('allow_questions', True)
            activity.never_answer_directly = options.get('never_answer_directly', True)
            activity.allow_emojis = options.get('allow_emojis', True)
            activity.trust_document = options.get('trust_document', True)
            activity.word_limit = options.get('word_limit', 0)
            
            activity.save(update_fields=[
                'questions', 'agent_attitude', 'subjects', 'restrict_to_subject',
                'allow_questions', 'never_answer_directly', 'allow_emojis', 
                'trust_document', 'word_limit'
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('simbaapp', '0004_add_options_field'),
    ]

    operations = [
        migrations.RunPython(
            migrate_to_options,
            reverse_migrate_from_options,
            hints={'simbaapp.Activity': 'Activity'}
        ),
    ]
