# Generated by Django 5.2 on 2025-07-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simbaapp', '0005_migrate_fields_to_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='agent_attitude',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='restrict_to_subject',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='allow_questions',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='never_answer_directly',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='allow_emojis',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='trust_document',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='word_limit',
        ),
    ]
