# Generated by Django 5.2 on 2026-09-06 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simbaapp', '0006_remove_old_activity_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('element_clicked', models.CharField(max_length=100)),
                ('reliance', models.FloatField(blank=True, null=True)),
                ('verif_epistemique', models.FloatField(blank=True, null=True)),
                ('verif_source', models.FloatField(blank=True, null=True)),
                ('selfeval', models.FloatField(blank=True, null=True)),
                ('prompt_qual', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_interactions', to='simbaapp.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_interactions', to='simbaapp.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
