# Generated by Django 5.2 on 2026-09-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simbaapp', '0007_dashboardinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ai_model',
            field=models.CharField(choices=[('gpt', 'GPT'), ('mistral', 'Mistral')], default='mistral', max_length=20),
        ),
    ]